"""
scraper/fixtures/judgment_corpus.py
-------------------------------------
Human-authored ground-truth corpus for the extraction pipeline regression suite.

Each entry contains:
  id             – unique identifier, matches the filename in fixtures/recordings/
  judgment_text  – sanitised/representative judgment excerpt in the source language
  truth_labels   – ground-truth field values authored BY READING THE JUDGMENT TEXT,
                   independently of any LLM response.  A recording that disagrees
                   with these labels will cause tests to fail.

The LLM responses for these texts live in fixtures/recordings/<id>.json.
They were generated by running ``python3 fixtures/record.py`` against the
real pipeline (see that script for provenance) and then human-reviewed for
correctness against these truth labels.

Do NOT derive truth_labels from a recording — read the judgment text first,
decide the correct classification, write the label, then check the recording
agrees.  This separation is what gives the tests their regression value.

Corpus coverage:
  1. English  — Vehicle Defect / Allowed              (high confidence)
  2. Hindi    — Service Deficiency / Partially Allowed (high confidence)
  3. Marathi  — Unfair Trade Practice / Dismissed     (high confidence)
  4. Tamil    — Finance / Insurance / Allowed         (high confidence)
  5. English  — Extended Warranty / AMC / Ex-parte    (high confidence)
  6. English  — EV / Settled / Withdrawn              (high confidence)
  7. Garbled  — low-confidence (< 0.35 threshold)
"""

CORPUS = [
    # ------------------------------------------------------------------ #
    # 1. English — Vehicle Defect, Allowed                                #
    #                                                                      #
    # Reading the text: complainant bought an Acme Metro (Sales context), #
    # engine knocking = Vehicle Defect / Engine / Engine & Transmission.  #
    # Commission allowed complaint → Allowed.  Dealer is Sunrise Motors.  #
    # ------------------------------------------------------------------ #
    {
        "id": "en-vehicle-defect-allowed",
        "judgment_text": (
            "DISTRICT CONSUMER DISPUTES REDRESSAL COMMISSION, PUNE\n"
            "Complaint No. CC/2022/1234\n\n"
            "The complainant purchased an Acme Metro from Sunrise Motors Pvt Ltd, "
            "Pune, on 15 March 2021 for Rs 6,50,000. Within two months of purchase "
            "the engine developed a persistent knocking noise. Despite three visits "
            "to the authorised service centre the defect was not rectified.\n\n"
            "The Commission allowed the complaint in its entirety. It found that "
            "the engine defect was a manufacturing defect under the Consumer "
            "Protection Act. The opposite party was directed to refund Rs 6,50,000 "
            "and pay Rs 10,000 towards litigation costs within 45 days."
        ),
        # Ground truth authored by reading the text above:
        "truth_labels": {
            "issue_type":       "Vehicle Defect",
            "sales_or_service": "Sales",
            "warranty_related": True,
            "product_model":    "Acme Metro",
            "is_ev":            False,
            "part_involved":    "Engine",
            "part_category":    "Engine / Transmission",
            "dealership":       "Sunrise Motors",
            "outcome":          "Allowed",
            # claim_amount not stated in this excerpt — omitted from assertions
            "amount_awarded":   660000.0,   # Rs 6,50,000 refund + Rs 10,000 costs
            "confidence_min":   0.85,
        },
    },

    # ------------------------------------------------------------------ #
    # 2. Hindi — Service Deficiency, Partially Allowed                    #
    #                                                                      #
    # Reading the text (Hindi): complainant brought car for service        #
    # (Service context), car held 45 days instead of 15, AC damaged =     #
    # Service Deficiency.  30k + 5k awarded out of 80k claimed →          #
    # Partially Allowed.  Dealer: Ram Motors.                              #
    # ------------------------------------------------------------------ #
    {
        "id": "hi-service-deficiency-partially-allowed",
        "judgment_text": (
            "जिला उपभोक्ता विवाद प्रतितोषण आयोग, जयपुर\n"
            "परिवाद संख्या CC/2023/456\n\n"
            "परिवादी ने अपनी एक्मे ट्रेलहॉक कार को राम मोटर्स प्राइवेट लिमिटेड, जयपुर के "
            "अधिकृत सेवा केंद्र पर जनरल सर्विस के लिए दिया था। सेवा केंद्र ने कार को "
            "15 दिन के बजाय 45 दिन तक रखा और वापस करते समय ए.सी. में नई खराबी आ गई "
            "थी। परिवादी ने रु. 80,000/- क्षतिपूर्ति की मांग की।\n\n"
            "आयोग ने पाया कि विरोधी पक्ष द्वारा सेवा में कमी की गई। आयोग ने "
            "विरोधी पक्ष को रु. 30,000/- क्षतिपूर्ति तथा रु. 5,000/- वाद व्यय "
            "अदा करने का आदेश दिया। शेष दावा अस्वीकार किया गया।"
        ),
        "truth_labels": {
            "issue_type":       "Service Deficiency",
            "sales_or_service": "Service",
            "warranty_related": False,
            "product_model":    "Acme Trailhawk",
            "is_ev":            False,
            "part_involved":    "Air Conditioner",
            "part_category":    "Electrical / AC",
            "dealership":       "Ram Motors",
            "outcome":          "Partially Allowed",
            "claim_amount":     80000.0,
            "amount_awarded":   35000.0,   # 30k + 5k costs
            "confidence_min":   0.80,
        },
    },

    # ------------------------------------------------------------------ #
    # 3. Marathi — Unfair Trade Practice, Dismissed                        #
    #                                                                      #
    # Reading the text (Marathi): complainant claims promised accessories  #
    # not delivered (Unfair Trade Practice / Sales).  Commission found no  #
    # proof → Dismissed.  No dealer identified, no award.                  #
    # ------------------------------------------------------------------ #
    {
        "id": "mr-unfair-trade-dismissed",
        "judgment_text": (
            "जिल्हा ग्राहक तक्रार निवारण आयोग, नागपूर\n"
            "तक्रार क्र. CC/2022/789\n\n"
            "तक्रारदाराने एक्मे मोटर्सची एक्मे स्पार्क कार खरेदी केली. विरुद्ध पक्षाने "
            "जाहिरातीत नमूद केलेली मोफत अॅक्सेसरीज न दिल्याचा आरोप तक्रारदाराने "
            "केला. मात्र विरुद्ध पक्षाने सादर केलेल्या विक्री करारानुसार अॅक्सेसरीज "
            "देण्याची अट नव्हती. तक्रारदाराने रु. 25,000/- नुकसान भरपाईची मागणी केली.\n\n"
            "आयोगाने तक्रार फेटाळली कारण विरुद्ध पक्षाने अनुचित व्यापार पद्धती "
            "अवलंबल्याचा कोणताही पुरावा सादर झाला नाही."
        ),
        "truth_labels": {
            "issue_type":       "Unfair Trade Practice",
            "sales_or_service": "Sales",
            "warranty_related": False,
            "product_model":    "Acme Spark",
            "is_ev":            False,
            "part_involved":    None,
            "part_category":    None,
            "dealership":       None,
            "outcome":          "Dismissed",
            "claim_amount":     25000.0,
            "amount_awarded":   None,
            "confidence_min":   0.80,
        },
    },

    # ------------------------------------------------------------------ #
    # 4. Tamil — Finance / Insurance, Allowed                              #
    #                                                                      #
    # Reading the text (Tamil): excess insurance premium charged on Acme  #
    # Ranger purchase = Finance / Insurance / Sales.  Full 45k + 3k costs #
    # awarded → Allowed.  Dealer: Selvam Automobiles.                      #
    # ------------------------------------------------------------------ #
    {
        "id": "ta-finance-insurance-allowed",
        "judgment_text": (
            "மாவட்ட நுகர்வோர் தகராறு தீர்ப்பாய கமிஷன், சென்னை\n"
            "புகார் எண்: CC/2023/321\n\n"
            "புகார்தாரர் ஏக்மி மோட்டார்ஸ் நிறுவனத்தின் ஏக்மி ரேஞ்சர் வாகனத்தை "
            "செல்வம் ஆட்டோமொபைல்ஸ், சென்னை மூலம் கடன் வசதியில் வாங்கினார். "
            "வாகன காப்பீட்டில் அறிவிக்கப்படாத அதிக பிரீமியம் வசூலிக்கப்பட்டதாக "
            "புகார்தாரர் குறை கூறினார். புகார்தாரர் ரூ. 45,000/- திருப்பித் தர "
            "கோரினார்.\n\n"
            "ஆணையம் புகார்தாரர் தரப்பில் சாதகமாக தீர்ப்பளித்து, எதிர் தரப்பினர் "
            "ரூ. 45,000/- மற்றும் ரூ. 3,000/- வழக்கு செலவுகளை செலுத்த உத்தரவிட்டது."
        ),
        "truth_labels": {
            "issue_type":       "Finance / Insurance",
            "sales_or_service": "Sales",
            "warranty_related": False,
            "product_model":    "Acme Ranger",
            "is_ev":            False,
            "dealership":       "Selvam Automobiles",
            "outcome":          "Allowed",
            "claim_amount":     45000.0,
            "amount_awarded":   48000.0,   # 45k + 3k costs
            "confidence_min":   0.80,
        },
    },

    # ------------------------------------------------------------------ #
    # 5. English — Extended Warranty / AMC, Ex-parte                      #
    #                                                                      #
    # Reading the text: AMC not honoured = Extended Warranty / AMC /      #
    # Service.  OP did not appear → Ex-parte.  12k refund + 5k comp       #
    # = 17k awarded.  Dealer: City Auto Service Centre.                    #
    # ------------------------------------------------------------------ #
    {
        "id": "en-warranty-exparte",
        "judgment_text": (
            "DISTRICT CONSUMER DISPUTES REDRESSAL COMMISSION, BHOPAL\n"
            "Complaint No. CC/2021/888\n\n"
            "Complainant purchased an Annual Maintenance Contract (AMC) for his Acme "
            "Vista from City Auto Service Centre, Bhopal, paying Rs 12,000 in "
            "advance. When he brought the vehicle for its scheduled service the "
            "opposite party wrongly claimed the AMC had expired and refused to honour "
            "it. The complainant specifically sought enforcement of the AMC contract. "
            "The opposite party, despite service of notice, failed to appear before "
            "the Commission. The Commission proceeded ex-parte and, holding the "
            "refusal to honour the AMC to be a deficiency under Extended Warranty / "
            "AMC terms, directed the opposite party to refund Rs 12,000 and pay "
            "Rs 5,000 as compensation."
        ),
        "truth_labels": {
            "issue_type":       "Extended Warranty / AMC",
            "sales_or_service": "Service",
            "warranty_related": True,
            "product_model":    "Acme Vista",
            "is_ev":            False,
            "dealership":       "City Auto Service Centre",
            "outcome":          "Ex-parte",
            "claim_amount":     12000.0,
            "amount_awarded":   17000.0,   # 12k + 5k
            "confidence_min":   0.85,
        },
    },

    # ------------------------------------------------------------------ #
    # 6. English — EV defect, Settled / Withdrawn                         #
    #                                                                      #
    # Reading the text: Acme Volt EV Max BMS defect → Vehicle Defect /    #
    # Electrical / AC / Sales.  Settled during appeal → Settled /         #
    # Withdrawn.  Battery replaced + 25k paid.  is_ev=True.               #
    # ------------------------------------------------------------------ #
    {
        "id": "en-ev-electrical-settled",
        "judgment_text": (
            "STATE CONSUMER DISPUTES REDRESSAL COMMISSION, GUJARAT\n"
            "Appeal No. A/2023/567\n\n"
            "The complainant purchased an Acme Volt EV Max from Volt Auto Ahmedabad "
            "for Rs 19,99,000 in January 2022. The vehicle's battery management system "
            "began showing errors within four months. The service centre could not "
            "replicate the fault initially, but on the third visit confirmed a BMS "
            "firmware defect. During pendency of the appeal both parties agreed to "
            "settle: Opposite Party agreed to replace the battery pack and pay "
            "Rs 25,000 towards inconvenience."
        ),
        "truth_labels": {
            "issue_type":       "Vehicle Defect",
            "sales_or_service": "Sales",
            "warranty_related": True,
            "product_model":    "Acme Volt EV Max",
            "is_ev":            True,
            "part_involved":    "Battery Management System",
            "part_category":    "Electrical / AC",
            "dealership":       "Volt Auto Ahmedabad",
            "outcome":          "Settled / Withdrawn",
            "claim_amount":     1999000.0,
            "amount_awarded":   25000.0,
            "confidence_min":   0.85,
        },
    },

    # ------------------------------------------------------------------ #
    # 7. Garbled / truncated text — expected low confidence               #
    #                                                                      #
    # Reading the text: only isolated words survive; no reliable fields   #
    # can be extracted.  Confidence should be below CONFIDENCE_THRESHOLD  #
    # (0.35).  All classification fields expected null.                   #
    # ------------------------------------------------------------------ #
    {
        "id": "low-confidence-garbled",
        "judgment_text": (
            "... [text extraction failed] ... vehicle ... Rs ... opposite party ..."
            " ... ordered ... ..."
        ),
        "truth_labels": {
            "issue_type":                None,
            "outcome":                   None,
            "confidence_max":            0.35,
            "expect_low_confidence_status": True,
        },
    },
]
