#!/usr/bin/env python3
"""
scraper/fixtures/record.py
---------------------------
Regenerate golden LLM-response recordings for the judgment corpus.

Run this script when:
  - The primary model changes and you want to capture new baseline responses
  - The prompt in extract.py changes and you need updated recordings
  - A new corpus entry is added to judgment_corpus.py

After running, REVIEW each new recording against the corresponding
truth_labels in judgment_corpus.py before committing.  Only commit a
recording that correctly classifies the judgment text according to the
human-authored truth labels.  A recording that disagrees with the truth
labels means the prompt or model has regressed and should NOT be committed.

Usage (from scraper/ directory):
    # Gemini (default):
    GEMINI_API_KEY=<key> python3 fixtures/record.py

    # OpenAI:
    OPENAI_API_KEY=<key> LLM_PRIMARY_PROVIDER=openai python3 fixtures/record.py

    # Specific corpus entry only:
    GEMINI_API_KEY=<key> python3 fixtures/record.py --id en-vehicle-defect-allowed
"""

import argparse
import json
import os
import sys

SCRAPER_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, SCRAPER_DIR)

import llm  # noqa: E402
from fixtures.judgment_corpus import CORPUS  # noqa: E402
import extract  # noqa: E402 — for SYSTEM_INSTRUCTION

RECORDINGS_DIR = os.path.join(os.path.dirname(__file__), "recordings")


def record_entry(entry: dict, force: bool = False) -> None:
    case_id = entry["id"]
    out_path = os.path.join(RECORDINGS_DIR, f"{case_id}.json")

    if os.path.exists(out_path) and not force:
        print(f"  [skip] {case_id} — recording exists (use --force to overwrite)")
        return

    print(f"  [record] {case_id} …", end=" ", flush=True)
    user_prompt = f"JUDGMENT TEXT:\n\n{entry['judgment_text']}"
    try:
        raw, in_tok, out_tok, label, model_used = llm.call_llm(
            extract.SYSTEM_INSTRUCTION,
            user_prompt,
            temperature=0.1,
        )
    except Exception as exc:
        print(f"FAILED: {exc}")
        return

    record = {
        "_provenance": (
            f"Generated by fixtures/record.py against {model_used} on "
            f"{__import__('datetime').datetime.utcnow().strftime('%Y-%m-%d')}. "
            "Human-reviewed: TODO — verify against truth_labels before committing."
        ),
        "raw_llm_response": raw,
    }
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(record, fh, ensure_ascii=False, indent=2)
    print(f"OK ({in_tok} in / {out_tok} out tokens, model={model_used})")
    print(f"         → {out_path}")
    print(f"         → RAW: {raw[:120]!r}{'…' if len(raw) > 120 else ''}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Record golden LLM responses for the judgment corpus")
    parser.add_argument("--id",    dest="entry_id", default=None,
                        help="Record only this corpus entry (default: all)")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing recording files")
    args = parser.parse_args()

    os.makedirs(RECORDINGS_DIR, exist_ok=True)
    llm.print_config()
    print()

    entries = CORPUS
    if args.entry_id:
        entries = [e for e in CORPUS if e["id"] == args.entry_id]
        if not entries:
            sys.exit(f"No corpus entry with id={args.entry_id!r}")

    for entry in entries:
        record_entry(entry, force=args.force)

    print("\n[record] Done.  Review each new recording against truth_labels before committing.")


if __name__ == "__main__":
    main()
